"""empty message

Revision ID: 839f3e709241
Revises: 8ff8d409041d
Create Date: 2019-01-12 20:44:25.704775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839f3e709241'
down_revision = '8ff8d409041d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column(u'form', sa.Column('id_user', sa.Integer(), nullable=True))
    op.add_column(u'form', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_form_timestamp'), 'form', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'form', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_index(op.f('ix_form_timestamp'), table_name='form')
    op.drop_column(u'form', 'timestamp')
    op.drop_column(u'form', 'id_user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
