"""empty message

Revision ID: 8ff8d409041d
Revises: 
Create Date: 2019-01-12 20:35:23.074187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff8d409041d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_description'), 'form', ['description'], unique=False)
    op.create_index(op.f('ix_form_title'), 'form', ['title'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('tipe', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_label'), 'question', ['label'], unique=False)
    op.create_index(op.f('ix_question_tipe'), 'question', ['tipe'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_form', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_form'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_email'), 'answer', ['email'], unique=False)
    op.create_index(op.f('ix_answer_timestamp'), 'answer', ['timestamp'], unique=False)
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_label'), 'option', ['label'], unique=False)
    op.create_table('answer_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_answer', sa.Integer(), nullable=True),
    sa.Column('id_option', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_answer'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['id_option'], ['option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_item')
    op.drop_index(op.f('ix_option_label'), table_name='option')
    op.drop_table('option')
    op.drop_index(op.f('ix_answer_timestamp'), table_name='answer')
    op.drop_index(op.f('ix_answer_email'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_tipe'), table_name='question')
    op.drop_index(op.f('ix_question_label'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_form_title'), table_name='form')
    op.drop_index(op.f('ix_form_description'), table_name='form')
    op.drop_table('form')
    # ### end Alembic commands ###
